name: Android CI  # Workflow name

on:
  push:
    branches: [ master ]  # Trigger on push to main branch
  pull_request:
    branches: [ master ]  # Trigger on pull request targeting main branch
  workflow_dispatch:
  
jobs:
  lint:
    runs-on ubuntu-latest
    steps:
      - nameCheckout the code
        uses: action/checkout@v2

      - name: Run Lint
        run : ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html
